[package]

name = "dinosaur"
version = "0.0.1"
authors = [ "Lucas Silva Sim√µes <simoes.lucas.silva@gmail.com>", "Paulo Roberto de Oliveira Castro <p.oliveira.castro@gmail.com>", "Rodrigo de Azeredo Orselli <rodrigo.orselli@gmail.com>" ]
